<?php

return [
    'estrupo',
    'estrupar',
    'estrupa',
    'caralho',
    'bunda',
    'hitler',
    'idiota',
    'bunda',
    'Idiota',
    'Desgraçado',
    'cadela',
    'sangrento',
    'besteira',
    'merda',
    'besteira',
    'filho da puta',
    'chupador de pau',
    'besteira',
    'boceta',
    'cyka blyat',
    'droga',
    'caramba',
    'pau',
    'idiota',
    'sapatona',
    'filho da puta',
    'Porra',
    'Maldito',
    'caramba',
    'inferno',
    'puta merda',
    'merda',
    'na merda',
    'kike',
    'filho da puta',
    'cu',
    'anus',
    'toba',
    'puta',
    'foda',
    'foda-se',
    'foder',
    'pariu',
    'nazista',
    'nazismo',
    'neonazismo',
    'neonazista',
    'odeio negro',
    'hitler',
    'anus',
    'arrombado',
    'asno',
    'babaca',
    'baita',
    'baleia',
    'baitola',
    'besta',
    'besteira',
    'bicha',
    'bichona',
    'bichona velha',
    'biscate',
    'boceta',
    'boiola',
    'bosta',
    'bostinha',
    'boçal',
    'burro',
    'bunda',
    'bundão',
    'bunduda',
    'cabeçudo',
    'cacete',
    'cadela',
    'cafajeste',
    'caga-regras',
    'cagão',
    'canalha',
    'capeta',
    'caralho',
    'caramba',
    'capiroto',
    'chifrudo',
    'chupador de pau',
    'cocô',
    'corno',
    'cretino',
    'crackudo',
    'cretino',
    'cruel',
    'cu',
    'cuzão',
    'cyka blyat',
    'degenerado',
    'demente',
    'débil mental',
    'desgraça',
    'desgraçado',
    'diabo',
    'doente',
    'droga',
    'egocêntrico',
    'escroto',
    'esnobe',
    'estrupa',
    'estrupar',
    'estrupo',
    'estúpido',
    'excremento',
    'fdp',
    'fedorento',
    'feioso',
    'filho da puta',
    'foda',
    'foda-se',
    'foder',
    'fudido',
    'fracassado',
    'frango',
    'frouxo',
    'gentalha',
    'golpista',
    'gordo imundo',
    'idiota',
    'imbecil',
    'imbecilóide',
    'impotente',
    'inútil',
    'inferno',
    'jumento',
    'kike',
    'lazarento',
    'lerdo',
    'lixo humano',
    'macaco',
    'mal amado',
    'mal educado',
    'maldito',
    'maluco',
    'merda',
    'mentecapto',
    'miserável',
    'misógino',
    'mongol',
    'mula',
    'na merda',
    'naba',
    'nazista',
    'nazismo',
    'neonazismo',
    'neonazista',
    'nojento',
    'nóia',
    'odeio negro',
    'ogro',
    'otário',
    'otário de merda',
    'palhaço',
    'paspalho',
    'pilantra',
    'piranha',
    'porra',
    'preto imundo',
    'prostituta',
    'puta',
    'puta merda',
    'puto',
    'quenga',
    'racista',
    'rato',
    'retardado',
    'sangrento',
    'sapatão',
    'sapatona',
    'satanás',
    'safado',
    'safadão',
    'seu lixo',
    'seu merda',
    'tapado',
    'toba',
    'tosco',
    'trouxa',
    'troll',
    'urubu',
    'vaca',
    'vadia',
    'vagabunda',
    'verme',
    'viado',
    'zé ninguém',
    'zé ruela',
    'xvideos',
    'x videos',
    'xxx',
    'cuceta'
];
